### ISSUE TITLE
main.py is missing in GKE palybook and requirement.txt is empty

### ISSUE THREAD

**Issue by shubham061292** [falcosecurity/kubernetes-response-engine#7]
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file main.py can't be loaded.
Did you list all required modules in requirements.txt?
Detailed stack trace: Traceback (most recent call last):
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 305, in check_or_load_user_function
    _function_handler.load_user_function()
  File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 184, in load_user_function
    spec.loader.exec_module(main)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/user_code/main.py", line 1, in <module>
    import playbooks
  File "/user_code/playbooks/__init__.py", line 3, in <module>
    import pendulum
ModuleNotFoundError: No module named 'pendulum'

**Comment by eihwaz-kob** [comment]
hi,
what command did you use exactly?
have you pipenv installed?
